name: develop

on:
  workflow_dispatch:
    branches: [ develop ]
  push:
    branches: [ develop ]
    paths:
      - 'GeographicLib/**'
      - 'GeographicLibTests/**'
      - 'GeographicLib.NET.sln'

jobs:
  build:
    name: Pre-release on ${{ matrix.os }}
    environment: Pre-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
        
    - name: Clean
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      id: test
      run:
        dotnet test -c Release --no-build --verbosity normal
      
    - name: Publish NugGet Package
      env:
        API_KEY: "${{ secrets.NUGET_API_KEY }}"
      run: |
        dotnet pack -c Release --no-build --version-suffix "preview-$(date +%Y%m%d%H%M%S)"
        cd ./GeographicLib/bin/Release/
        dotnet nuget push *.nupkg -k $API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
      
